version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./backend/auth-microservice
    container_name: auth_service
    ports:
      - "50051:50051"
    environment:
      - DB_URL=postgres://booking_user:secret@postgres:5432/booking?sslmode=disable
      - JWT_SECRET=qklgmakjegnjkeahgnjkaegnejk214124
      - AUTH_SERVICE_PORT=50051
      - ADMIN_LOGIN=admin
      - ADMIN_PASSWORD=admin
    depends_on:
      - postgres

  booking-service:
    build: ./backend/booking
    container_name: booking_service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booking
      - SPRING_DATASOURCE_USERNAME=booking_user
      - SPRING_DATASOURCE_PASSWORD=secret
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=50051
    depends_on:
      - postgres
      - auth-service

  frontend:
   build: ./frontend
   container_name: frontend
   ports:
     - "3000:5173"
   restart: unless-stopped
   environment:
     - VITE_API_URL=http://localhost:8080
   depends_on:
     - booking-service

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
